### ISSUE TITLE
Ubuntu18.04+Qt5.12.3需要修改代码才能运行

### ISSUE THREAD

**Issue by hxhlb** [jaredtao/TaoQuick#2]
Ubuntu 18.04 + Qt5.12.3 环境, 编译代码后运行, 会出现
```cpp
......
qglx_findConfig: Failed to finding matching FBConfig (8 8 8 8)
qglx_findConfig: Failed to finding matching FBConfig (1 8 8 8)
......
```
错误, 并且界面卡住无显示内容.

经过搜索stackoverflow, 需要将TaoQuickDemo中的main.cpp中的代码
```cpp
QSurfaceFormat fmt = QSurfaceFormat::defaultFormat();
fmt.setSamples(4);
```
修改为
```cpp
QSurfaceFormat fmt = QSurfaceFormat::defaultFormat();
// fmt.setSamples(4);
fmt.setVersion(3, 0);
```

修改后即可正常运行查看效果.

具体为什么这样修改, 不是很清楚, 希望能有人帮忙解释一下.

**Comment by jaredtao** [comment]
你这是把OpenGL的版本设置为3.0了。
OpenGL版本和硬件、系统驱动关系都很大。
Qt内部有设置版本（忘了是多少），在你的系统估计跑不起来。
可以试试更新显卡驱动，或者更新一下OpenGL库。
显卡驱动在系统设置里面。
OpenGL库大概是这两个： glew-dev  glfw-dev
