### ISSUE TITLE
CusComboBox 求支持textRole，valueRole

### ISSUE THREAD

**Issue by hzysoft** [jaredtao/TaoQuick#24]
当我设置textRole，valueRole时，下拉列表显示空白的
但是选择数据之后是正常显示当前已选。

原生combobox没有这个问题，

求解决！

**Comment by jaredtao** [comment]
请 贴一下具体的代码。
我正常使用，未出现你说的问题。
示例代码如下：
`            CusComboBox {
                model: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
                width: 120
                displayText: qsTr(currentText)
            }
`

**Comment by hzysoft** [comment]
model 是数组没问题，我用了textRole，valueRole，model是ListModel就会出问题，这个控件不是继承自combobox吗，理论应该支持listmodel

代码如下：


`
ComboBox {
                        id: comboBox3
                        width: 120
                        height: 26
                        textRole: "name"
                        valueRole: "cost"
                        font.pixelSize: 10
                        model: holdersType
                    }

ListModel {
        id: holdersType
          ListElement {
                   name: "Apple"
                   cost: 2.45
               }
               ListElement {
                   name: "Orange"
                   cost: 3.25
               }
               ListElement {
                   name: "Banana"
                   cost: 1.95
               }
    }

`

**Comment by jaredtao** [comment]
抱歉耽误了几天，问题已修复。
更新代码即可。
--------------------------------------------------------------------------
是我的代码问题，没有考虑到js对象的兼容性。

代码中数据访问的部分：
```qml
ComboBox {

  .....

 delegate: ItemDelegate {
        .....
        contentItem: CusLabel {
             .....
            text: qsTr(String(modelData)) + CusConfig.transString
            .....
        }
 }
}
```

修改为

```qml
ComboBox {

  .....

 delegate: ItemDelegate {
        .....
        contentItem: CusLabel {
             .....
            property var dData : cusComboBox.textRole ? (Array.isArray(cusComboBox.model) ? modelData[cusComboBox.textRole] : model[cusComboBox.textRole]) : modelData
            text: qsTr(String(dData)) + CusConfig.transString
            .....
        }
 }
}
```

modelData 是一般的数据访问方式，js的数组使用modelData[textRole] 这种，js的object 使用model[textRole]，
ListModel 对应的是js object。
