### ISSUE TITLE
在设计界面报错 无法使用控件

### ISSUE THREAD

**Issue by poyiduanhui** [jaredtao/TaoQuick#3]
已经在 qt的目录存在 模块 qml/TaoQuick 
但是在设计界面的时候 编译器 报错  只能删除 import TaoQuick 1.0
编译器 是 MinGW  版本   qt版本是5.12.3

Automatic type dump of QML module failed.
Errors:
"D:\QT\5.12.3\mingw73_64\bin\qmlplugindump.exe" returned exit code 3.
Arguments: -nonrelocatable TaoQuick 1.0 .
Found a dependency on Qt.labs.folderlistmodel with two major versions:1.0 and 2.1 which is unsupported, discarding smaller version
Found a dependency on QtQuick.Controls with two major versions:1.1 and 2.12 which is unsupported, discarding smaller version
Found a dependency on QtQuick.Controls with two major versions:1.1 and 2.5 which is unsupported, discarding smaller version
QQmlComponent: Component is not ready
file:///D:/QT/5.12.3/mingw73_64/qml/typelist.qml:23:1: module "TaoQuick" plugin "TaoQuick" not found

**Comment by jaredtao** [comment]
按你的错误信息，再确认一下，你的D:\QT\5.12.3\mingw73_64\qml\TaoQuick文件夹要有，里面要有TaoQuick.dll，注意不是带d的TaoQuickd.dll。带d的是debug模式的，要用release模式不带d的。

**Comment by jaredtao** [comment]
抱歉，我忘记修改安装配置的pri文件了，少安装了一些文件。已经修复并提交，获取最新的代码，make install就可以了。

**Comment by poyiduanhui** [comment]
嗯 我再试试

**Comment by poyiduanhui** [comment]
在安装提示中
TaoQuick _dll的使用

**将bin/TaoQuick文件夹复制到你的可执行程序同级目录下***

建议改成TaoQuick-master\bin 中 debug 和release 中的TaoQuick文件 分别放在 构建后项目的对应的 debug 和 release 文件下

**Comment by poyiduanhui** [comment]
已经可以在设计界面中使用了 谢谢你
