### ISSUE TITLE
关于TaoQuick增加输入框，对话框相关的组件

### ISSUE THREAD

**Issue by CppLizard** [jaredtao/TaoQuick#4]
涛哥你好
最近我打算用QML写一个项目，发现QML自带的组件控件不满足我的需求，都是需要自己造轮子实现，然后通过查找大量资料发现TaoQuick组件库已经很好的封装了很多常用的组件，不过使用过程中还发现缺少输入框，对话框等相关组件的封装，涛哥有时间能否封装一下这些组件，最后非常感谢TaoQuick大大减少了我的工作量，也感谢涛哥的开源精神！！

**Comment by jaredtao** [comment]
文件选择对话框有的。
弹窗也有一种。
输入框默认的，我以为够用了。
我找时间看一下其它组件库，做几个吧。
