### ISSUE TITLE
界面整体向右下偏移 出现黑边

### ISSUE THREAD

**Issue by inkydragon** [jaredtao/TaoQuick#8]
效果如图
![image](https://user-images.githubusercontent.com/5158738/106164059-8d7a0300-61c4-11eb-9eb8-5a4103647966.png)

并且标题栏上的功能按钮还是需要在原位置按才有效。

日志
> 2021-01-28 23:56:09 QWindowsWindow::setGeometry: Unable to set geometry 2520x1680+917-716 (frame: 2520x1680+917-716) on TaoFrameLessView/"" on "\\.\DISPLAY1". Resulting geometry: 2908x2352+917-716 (frame: 2908x2352+917-716) margins: 0, 0, 0, 0 minimum size: 800x600 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=1400,1050 maxtrack=0,0)

完整日志：[2021-01-28_23_log.html.log](https://github.com/jaredtao/TaoQuick/files/5888457/2021-01-28_23_log.html.log)

**Comment by jaredtao** [comment]
是必现的吗?能否说明一下，操作系统版本和屏幕分辨率

**Comment by KyleYe** [comment]
同样的问题，Windows10 20H2版本，屏幕1080*1290

**Comment by zhlgh603** [comment]
TaoFrameLessView::TaoFrameLessView(QWindow *parent) : QQuickView(parent), d(new TaoFrameLessViewPrivate)
{
    setFlags(Qt::CustomizeWindowHint | Qt::Window | Qt::FramelessWindowHint | Qt::WindowMinMaxButtonsHint | Qt::WindowTitleHint | Qt::WindowSystemMenuHint);
    setResizeMode(SizeRootObjectToView);

//    d->setBorderLess((HWND)(winId()), d->borderless);  //这里产生了黑边，注释掉

**Comment by jaredtao** [comment]
暂时屏蔽掉setBorderLess 函数，不会黑边了，边框也不能拖动了。找到完整的解决方案，再加边框拖动
